sudo: required
services:
  - docker

before_install:
  - docker build -t lennykamande/mern-stack -f Dockerfile.env .

script:
  - docker run lennykamande/mern-stack npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-34567920827"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"